/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.calcular_nota_estudiante.vista;

import com.calcular_nota_estudiante.controlador.ControladorEstudiante;
import com.calcular_nota_estudiante.controlador.ControladorUsuario;
import com.calcular_nota_estudiante.execepciones.UsuarioExcepcion;
import com.calcular_nota_estudiante.modelo.Estudiante;
import com.calcular_nota_estudiante.modelo.Usuario;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanv
 */
public class MDINota_Estudiante extends javax.swing.JFrame {
    
    private ControladorUsuario controlUsuarios;
    private Usuario usuarioAutenticado;
    private ControladorEstudiante controlEstudiante;

    /**
     * Creates new form MDINota_Estudiante
     */
    public MDINota_Estudiante() {        
        initComponents();// crear todas las instancias
        controlarEstadoMenus();
        controlUsuarios = new ControladorUsuario();
        txtCorreo.setText("valentin@umanizales.edu.co");
        txtContrasenia.setText("1234567");
    }
    
    
    
    private void llenarEstudiantes()
    {
        //Extrae el modelo de la tabla (Columnas y filas)
        DefaultTableModel model = (DefaultTableModel) tblEstudiantes.getModel();
        //Limpia toda la tabla
        model.getDataVector().removeAllElements();
        //Declara un arreglo de objetos para representar una fila de la tabla
        //Object[] fila = {"234342","Juan Valentin",4000000, false};
        // Adicionar la fila a la tabla
        //model.addRow(fila);
        //Refrescar la tabla
        
        //Recorriendo el controlador de empleados y llenando mi tabla
        for(Estudiante est: controlEstudiante.getEstudiante())
        {
            if(est!=null)
            {
                Object[] fila = {est.getNombre(),est.getCodigo(),est.getCarrera()};
                model.addRow(fila);
            }       
        }        
        tblEstudiantes.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void controlarEstadoMenus (){
        
            mnuListaEstudiantes.setEnabled(false);
            mnuDiagramaNotas.setEnabled(false);
            mnuCalcularNota.setEnabled(false);
            
            mnuListaEstudiantes.setVisible(false);
            mnuCalcularNota.setVisible(false);
            mnuDiagramaNotas.setVisible(false);
        
        if(usuarioAutenticado!= null)
        {        
            //Evaluar el rol
            switch(usuarioAutenticado.getRol().getCodigo())
            {
                case 1:
                    mnuListaEstudiantes.setEnabled(true);
                    mnuDiagramaNotas.setEnabled(true);
                    mnuCalcularNota.setEnabled(true);
                    
                    mnuListaEstudiantes.setVisible(true);
                    mnuDiagramaNotas.setVisible(true);
                    mnuCalcularNota.setVisible(true);
                    break;
                
                case 2:
                    mnuListaEstudiantes.setEnabled(true);
                    mnuListaEstudiantes.setVisible(true);
                    break;
                    
            }            
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        jifLogin = new javax.swing.JInternalFrame();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        jifCalcularNota = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNotaTotal = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota4 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtAsignatura = new javax.swing.JTextField();
        txtSemestre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jifListaEstudiantes = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNotaAsignatura = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuListaEstudiantes = new javax.swing.JMenuItem();
        mnuCalcularNota = new javax.swing.JMenuItem();
        mnuDiagramaNotas = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifLogin.setIconifiable(true);
        jifLogin.setMaximizable(true);
        jifLogin.setResizable(true);
        jifLogin.setTitle("Ingreso a Calculo Nota");
        jifLogin.setVisible(true);

        txtCorreo.setText("valentin@umanizales.edu.co");
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtContrasenia.setText("1234567");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblUsuario.setText("*Correo");

        lblContrasenia.setText("*Contrasenia");

        javax.swing.GroupLayout jifLoginLayout = new javax.swing.GroupLayout(jifLogin.getContentPane());
        jifLogin.getContentPane().setLayout(jifLoginLayout);
        jifLoginLayout.setHorizontalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifLoginLayout.createSequentialGroup()
                        .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContrasenia)
                            .addComponent(lblUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jifLoginLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnIngresar)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jifLoginLayout.setVerticalGroup(
            jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jifLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasenia)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnIngresar)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        desktopPane.add(jifLogin);
        jifLogin.setBounds(110, 50, 410, 270);

        jifCalcularNota.setClosable(true);
        jifCalcularNota.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifCalcularNota.setIconifiable(true);
        jifCalcularNota.setMaximizable(true);
        jifCalcularNota.setResizable(true);
        jifCalcularNota.setTitle("Calcular nota");
        jifCalcularNota.setVisible(false);

        tblNotas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        }
        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "semestre", "Asignatura", "nota 1", "nota 2", "nota 3", "nota 4"
            }
        ));
        tblNotas.getTableHeader().setResizingAllowed(false);
        tblNotas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblNotas);

        tblNotaTotal = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }}
            tblNotaTotal.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null}
                },
                new String [] {
                    "Nombre", "Codigo", "Semestre", "Asignatura", "NT"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            tblNotaTotal.getTableHeader().setResizingAllowed(false);
            tblNotaTotal.getTableHeader().setReorderingAllowed(false);
            jScrollPane3.setViewportView(tblNotaTotal);

            jButton3.setText("Calcular nota");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton4.setText("Listo");

            jButton5.setText("Salir");

            txtSemestre.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtSemestreActionPerformed(evt);
                }
            });

            jLabel5.setText("Nombre");

            jLabel6.setText("Codigo");

            jLabel7.setText("Semestre");

            jLabel8.setText("Asignatura");

            jLabel9.setText("Nota 1");

            jLabel10.setText("Nota 3");

            jLabel11.setText("Nota 2");

            jLabel12.setText("Nota 4");

            javax.swing.GroupLayout jifCalcularNotaLayout = new javax.swing.GroupLayout(jifCalcularNota.getContentPane());
            jifCalcularNota.getContentPane().setLayout(jifCalcularNotaLayout);
            jifCalcularNotaLayout.setHorizontalGroup(
                jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(26, 26, 26)
                                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(213, 213, 213)
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCalcularNotaLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCalcularNotaLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18))
                                        .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addComponent(txtNota4)))))
                        .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(2, 107, Short.MAX_VALUE))
            );
            jifCalcularNotaLayout.setVerticalGroup(
                jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifCalcularNotaLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9))
                    .addGap(18, 18, 18)
                    .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(14, 14, 14)
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(jifCalcularNotaLayout.createSequentialGroup()
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jifCalcularNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton3)
                    .addGap(25, 25, 25)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton4)
                    .addGap(1, 1, 1)
                    .addComponent(jButton5)
                    .addGap(19, 19, 19))
            );

            desktopPane.add(jifCalcularNota);
            jifCalcularNota.setBounds(20, 10, 560, 390);

            jifListaEstudiantes.setClosable(true);
            jifListaEstudiantes.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
            jifListaEstudiantes.setIconifiable(true);
            jifListaEstudiantes.setMaximizable(true);
            jifListaEstudiantes.setResizable(true);
            jifListaEstudiantes.setTitle("Lista de Estudiantes");
            jifListaEstudiantes.setVisible(false);

            tblEstudiantes = new javax.swing.JTable()
            {
                public boolean isCellEditable(int rowIndex, int colIndex){
                    return false;
                }
            }
            tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String [] {
                    "Nombre", "Semestre", "Codigo"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            tblEstudiantes.getTableHeader().setResizingAllowed(false);
            tblEstudiantes.getTableHeader().setReorderingAllowed(false);
            jScrollPane1.setViewportView(tblEstudiantes);

            jLabel2.setText("Lista de Los estudiantes de Quinto y Sexto Semestre, de la carrera de Ingenieria de Sistemas.");

            jLabel3.setText("Ver Nota:");

            jButton1.setText("Calcular");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jInternalFrame1.setVisible(true);

            tblNotaAsignatura.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null, null}
                },
                new String [] {
                    "Nombre", "Semestre", "Codigo", "Programacion", "Matematicasl", "Fisica"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            tblNotaAsignatura.getTableHeader().setResizingAllowed(false);
            tblNotaAsignatura.getTableHeader().setReorderingAllowed(false);
            jScrollPane4.setViewportView(tblNotaAsignatura);

            jLabel4.setText("La nota de tus asignaturas son");

            jButton2.setText("Salir");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
            jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
            jInternalFrame1Layout.setHorizontalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jLabel4))
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(186, 186, 186)
                                    .addComponent(jButton2)))
                            .addGap(0, 182, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jInternalFrame1Layout.setVerticalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton2)
                    .addContainerGap(148, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jifListaEstudiantesLayout = new javax.swing.GroupLayout(jifListaEstudiantes.getContentPane());
            jifListaEstudiantes.getContentPane().setLayout(jifListaEstudiantesLayout);
            jifListaEstudiantesLayout.setHorizontalGroup(
                jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jifListaEstudiantesLayout.setVerticalGroup(
                jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                    .addGroup(jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel1))
                        .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addGroup(jifListaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jButton1)))
                        .addGroup(jifListaEstudiantesLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(28, Short.MAX_VALUE))
            );

            desktopPane.add(jifListaEstudiantes);
            jifListaEstudiantes.setBounds(20, 10, 550, 608);

            mnuArchivo.setMnemonic('f');
            mnuArchivo.setText("Inicio");

            mnuListaEstudiantes.setMnemonic('o');
            mnuListaEstudiantes.setText("Lista Estudiantes");
            mnuListaEstudiantes.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuListaEstudiantesActionPerformed(evt);
                }
            });
            mnuArchivo.add(mnuListaEstudiantes);

            mnuCalcularNota.setMnemonic('a');
            mnuCalcularNota.setText("Calcular Nota");
            mnuCalcularNota.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuCalcularNotaActionPerformed(evt);
                }
            });
            mnuArchivo.add(mnuCalcularNota);

            mnuDiagramaNotas.setMnemonic('a');
            mnuDiagramaNotas.setText("Diagramas De Notas");
            mnuDiagramaNotas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuDiagramaNotasActionPerformed(evt);
                }
            });
            mnuArchivo.add(mnuDiagramaNotas);

            mnuSalir.setMnemonic('x');
            mnuSalir.setText("Salir");
            mnuSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuSalirActionPerformed(evt);
                }
            });
            mnuArchivo.add(mnuSalir);

            menuBar.add(mnuArchivo);

            setJMenuBar(menuBar);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed

        JOptionPane.showMessageDialog(rootPane,"Gracias por utilizar mi app. Vuelve pronto");
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuDiagramaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDiagramaNotasActionPerformed
        // TODO add your handling code here:
                    
    }//GEN-LAST:event_mnuDiagramaNotasActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

    try {
            usuarioAutenticado= controlUsuarios.verificarUsuario(txtCorreo.getText(), txtContrasenia.getText()); 
            // Es porque todo esta bien
            controlarEstadoMenus();
            jifLogin.hide();
            
            JOptionPane.showMessageDialog(rootPane, "Bienvenido "
                    +usuarioAutenticado.getNombre(), "Ingreso Exitoso",1);
            
        } catch (UsuarioExcepcion ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage(),"Error",0);
        }
    
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void mnuCalcularNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularNotaActionPerformed
        // TODO add your handling code here:
        if(jifCalcularNota.isIcon())
        {
            try {
                jifCalcularNota.setIcon(Boolean.FALSE);
            } catch (PropertyVetoException ex) {
                System.out.println("No se encontraba minimizado");
            }
        }
        jifCalcularNota.show();
    }//GEN-LAST:event_mnuCalcularNotaActionPerformed

    private void mnuListaEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaEstudiantesActionPerformed
        // TODO add your handling code here:
        if(jifListaEstudiantes.isIcon())
        {
            try {
                jifListaEstudiantes.setIcon(Boolean.FALSE);
            } catch (PropertyVetoException ex) {
                System.out.println("No se encontraba minimizado");
            }
        }
        jifListaEstudiantes.show();
    }//GEN-LAST:event_mnuListaEstudiantesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemestreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDINota_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDINota_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDINota_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDINota_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDINota_Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JInternalFrame jifCalcularNota;
    private javax.swing.JInternalFrame jifListaEstudiantes;
    private javax.swing.JInternalFrame jifLogin;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuCalcularNota;
    private javax.swing.JMenuItem mnuDiagramaNotas;
    private javax.swing.JMenuItem mnuListaEstudiantes;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTable tblNotaAsignatura;
    private javax.swing.JTable tblNotaTotal;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables

}
